matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    services:
    - docker
    cache:
      directories:
      - "$HOME/.npm"
      - ".git"
    env:
    - builder=travis
language: node_js
node_js:
- 8
addons:
  apt:
    packages:
    - curl
    - socat
    - time
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm install -g eslint gatsby-cli gh-pages;
  fi
script:
- npm i
- /bin/bash -l -c "/usr/bin/time -v make -e ci"
  #- npm run lint
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: false
    local-dir: public
    target-branch: master
    fqdn: kubash.org
    verbose: true
    on:
      branch: gatsby
  - provider: surge
    project: ./public/
    domain: kubash.org
    on:
      branch: gatsby
